### ISSUE TITLE
0.4.0 ignores config

### ISSUE THREAD

**Issue by giorgiga** [mierak/rmpc#103]
I edited my config but I don't seem to be able to have rmpc consider it:

```ron
$ < ~/.config/rmpc/config.ron grep Left
            "<Left>":  Left,
            "h":       Left,
$ rmpc config | grep Left
            "<Left>":  PreviousTab,
            "h":       Left,
$ rmpc --config ~/.config/rmpc/config.ron config | grep Left
            "<Left>":  PreviousTab,
            "h":       Left,
```

Am I doing something wrong?

I'm on version 0.4.0 (nixos has not updated the package to 0.5.0 yet)

**Comment by mierak** [comment]
Can you please provide your config.ron as well as output of `rmpc debuginfo` and /tmp/rmpc.log generated after you start rmpc? Maybe also check whats inside your `$XDG_CONFIG_HOME`.

> $ rmpc --config ~/.config/rmpc/config.ron config | grep Left

not sure what youre trying to do here but it should be either `rmpc --config ~/.config/rmpc/config.ron` or `rmpc -c ~/.config/rmpc/config.ron`

**Comment by giorgiga** [comment]
I was trying to show that `rmpc config` prints different values than the ones in my config file, but I now realize that it's supposed to print the *default* configuration (I thought it printed the *current* one).

Leaving that alone, `/tmp/rmpc.log` clearly says the problem is that my config is missing the "address" field (I thought omitting it would use the default value)... apologies: I didn't know there was a log.

Thanks for your help!

```
$ cat /tmp/rmpc.log
2024-10-22T23:14:25.304916153Z DEBUG src/main.rs:147 message="rmpc started" rev="0.4.0" 
2024-10-22T23:14:25.305035718Z WARN  src/main.rs:156 message="Failed to read config. Using default values. Check logs for more information" err="79:1: Unexpected missing field `address` in `ConfigFile`" 
...
```

**Comment by mierak** [comment]
Yup! It prints the default values and is intended to bootstrap your config, maybe a switch to print the current config could be added though. Rmpc should use a default value for address starting with [this change](https://github.com/mierak/rmpc/commit/d7d5b5c276295b7ba356661d65f622e47b37902a#diff-b0ba3e54b6f5ef1fa6aed8075e352a68fda66067fbafa8421042a2347801338aR92) meaning `v0.5.0`.

Glad you resolved the issue!
