### ISSUE TITLE
Show metadata of current song in queue view

### ISSUE THREAD

**Issue by soifou** [mierak/rmpc#107]
### Description

When I browse my playlist, sometimes I want to get details of a song. 

For now the shortest way is to go to the Album tab, find the album then select the song to display its metadata in the third pane.

Not very handy while ncmpcpp has a mnemonic `i` shortcut that will display the info of the song.

### Proposed solution

Similar to `ShowHelp` or `ShowOutput`, add a new action (`ShowMetadata` or `ShowInfo` ?) that will open a popup with all the metadata of the selected song in the queue view, configurable from the config file in `keybinds.queue`.

**Comment by mierak** [comment]
Sounds great to me. https://github.com/mierak/rmpc/pull/108 is in master, can you try it if it works as you wanted?

![image](https://github.com/user-attachments/assets/34b4d7f0-06da-4f90-8219-76255e62727d)

**Comment by soifou** [comment]
Thanks that's great! 

A minor issue though, when the terminal is not as wide as it should be, the text in the columns get truncated:

![image](https://github.com/user-attachments/assets/7005f761-c64e-4ec2-8b08-1e2b849c8260)

I see some way to resolve this:
- wrap text
- allow to scroll horizontally
- at certain terminal column size, the popup could take the whole width

Or workaround: reduce font size :)

**Comment by mierak** [comment]
Right, I know about that, its also not the only place this problem exists in, but I have no one size fits all solution for it since it is not handled by ratatui in any sort of ergonomic way.
I dont really like the idea of horizontal scroll and the popup taking the whole width just offsets the problem a bit but does not solve it.

Anyway, I introduced `textwrap` crate in https://github.com/mierak/rmpc/pull/109 and cooked up solution for this specific case. It is still not completely ideal, but should be workable I think.

**Comment by soifou** [comment]
It is, problem gone! I second the "textwrap" solution.

Anyway TYSM for this, you fullfill the request greatly, closing :)

**Comment by ionnux** [comment]
I feel like this should not be limiter to queue only.

**Comment by soifou** [comment]
Where else will you see a use?

**Comment by ionnux** [comment]
I meant in the other teams as well i.e. albums, artist tab e.t.c. As long as the cursor is on a song.

**Comment by soifou** [comment]
I don't get it, aren't the metadata show up already in the third pane automatically for you? What's the benefit of duplicating information?

**Comment by mierak** [comment]
I agree that the song metadata is already be present in the other panes. The curent use case is also tied to the internal state of the queue pane (selected song).

One thing I can see an argument for would be a global action to display the popup with info about the currently playing song if any.

**Comment by mierak** [comment]
@ionnux I have implemented `ShowCurrentSongInfo` global action which will display the same modal window with the metadata of the currently playing song. Its bound to `I` by default. https://github.com/mierak/rmpc/pull/112
