### ISSUE TITLE
ANSI/Unicode block image graphics support

### ISSUE THREAD

**Issue by 11xx** [mierak/rmpc#110]
### Description

https://github.com/atanunq/viuer (rust library)

For rendering images as terminal blocks. It also supports Kitty and Sixel but the blocks feature would be cool as a "last resort". It even "works" on the tty (with 8 colors lol).

**Comment by mierak** [comment]
Yeah something like this is somewhere on my todo list. Either through reimplementation or by offloading it to Chafa. Still undecided on that.
But its not too high on the list since ueberzugpp should cover most bases I think.

**Comment by 11xx** [comment]
> ueberzugpp should cover most bases I think.

It does.

I didn't know about Chafa, it also looks sharper than viu.

Thanks.

(Changed the title to make it generic, also closing as stale to not clutter :p)
