### ISSUE TITLE
Root level of any tab reset current position

### ISSUE THREAD

**Issue by soifou** [mierak/rmpc#116]
### Description

I don't know if this is intended but the **root** level of any tab does not keep the current user position in the list when switching back and forth. Sublevel does (albums of an artist, songs of an album).

The Queue tab behave differently since it will jump to the current playing song, not the first item.

### Steps to reproduce

Root level case:

- Go to `Artists` tab
- Select the second one 
- Go to another tab then come back to this tab
- The first item is selected

Sublevel case:

- Go to `Artists` tab
- Select an artist with several albums
- Select the second one
- Go to another tab then come back to this tab
- The position remains

### Expected behavior

I think the expected behaviour would be to always keep the last position in any tab, no matter what level we are.

In the Queue tab, it needs then to have an action to jump to the current song.

### rmpc debuginfo

no relevant

### Config file

no relevant

### Relevant log output

no relevant

**Comment by mierak** [comment]
Yeah I knew about the root level issue and completely forgot. It requires some logic to determine whether its the very first render or not, thanks for reminding me.

For the Queue/Tab pane, fair point, makes more sense to do it as you describe I think.

**Comment by mierak** [comment]
Hopefully solved, the new action is `JumpToCurrent` in Queue.

Thanks again, you have been a huge help so far!

**Comment by soifou** [comment]
Works like a charm :) well done @mierak you rock!
