### ISSUE TITLE
implement the MediaPlayer2 Interface

### ISSUE THREAD

**Issue by cn-kali-team** [mierak/rmpc#123]
### Description

First of all, thanks for the best music player ever 😎
I used [i3status-rs](https://docs.rs/i3status-rs/latest/i3status_rs/blocks/music/index.html) to display the current song in my i3 status bar. Is there a plan to implement the MediaPlayer2 interface.

**Comment by mierak** [comment]
Do you mean MPRIS? There is [mpd-mpris](https://github.com/natsukagami/mpd-mpris) already. Im not sure rmpc is the right place for that. Or why does mpd-mpris not work for you?

**Comment by cn-kali-team** [comment]
Thank you for your suggestion. I have tried `mpd-mpris`, but the status bar is not working.

```bash
➜  mpd-mpris -no-instance
mpd-mpris running
➜  busctl --user list | grep "org.mpris.MediaPlayer2." | cut -d' ' -f1
org.mpris.MediaPlayer2.mpd
```
 Maybe I should submit an issue to i3status-rs

**Comment by mierak** [comment]
You can try mpDris2, its directly recommended by the i3status.
