### ISSUE TITLE
Add "Play song under cursor" in other tabs

### ISSUE THREAD

**Issue by FLchs** [mierak/rmpc#133]
### Description

When browsing songs, there is no straightforward way to just play the selected song without adding it to the queue and then going to the queue tab to play it.

### Proposed solution

Adding a Keybind to "Play song under cursor" in other tabs would be nice.

I'm aware that it can be achieved using ExternalCommand but it seems a bit strange for a music player to not have the "play now" feature.

PS: Thanks for the nice work

**Comment by mierak** [comment]
How would this interact with directories and selected/marked files files?
I see two options:
1. simply ignore them and only care about single songs
2. add all songs but play the first one

The first option is simple, not sure about the second one from the top of my head. Also if we go with the second one, an "add all and play first" action should probably be added as well for the sake of consistency.

And thank you for enjoying rmpc!

**Comment by soifou** [comment]
> How would this interact with directories and selected/marked files files?

The "add all and play first" feels weird to me.

In my opinion, the KISS way:
- If we are in marking mode, do nothing. 
- If it's a selected directory, open it. 
- If it's a song play it.

And that would match OP's request I think.

**Comment by mierak** [comment]
Makes sense to me, what do you think about reusing the `Confirm` keybind for that, since its `Enter` by default, is what ncmpcpp does for this functionality and is not used in the browser panes.

**Comment by soifou** [comment]
Yup, adding a `Confirm` in `ui/browser` was exactly what I thought too :)

**Comment by mierak** [comment]
fixed in https://github.com/mierak/rmpc/pull/134
