### ISSUE TITLE
Swap `single` and `consume` keybinds

### ISSUE THREAD

**Issue by 42Willow** [mierak/rmpc#145]
Either this or change the order of single and consume in the top right
![image](https://github.com/user-attachments/assets/34a0618b-c27d-44a5-92f8-d3fcafef0fa9)

currently:
<kbd>z</kbd> corresponds with repeat
<kbd>x</kbd> corresponds with random
<kbd>c</kbd> corresponds with single, but should be consume
<kbd>v</kbd> corresponds with consume, but should be single

the issue is the positions of the keybinds on the keyboard do not align with the position of the song actions in the UI

**Comment by mierak** [comment]
fixed, thanks
