### ISSUE TITLE
Multi-select in queue for reordering

### ISSUE THREAD

**Issue by ralmachado** [mierak/rmpc#155]
### Description

Like in ncmpcpp, it would be useful to select multiple tracks to move up and down the current queue.

### Proposed solution

Use the same multiple selection as in the other tabs to pick tracks in the current queue, and allow movement of these tracks in the queue.

**Comment by mierak** [comment]
Sounds good!

**Comment by mierak** [comment]
Implemented in https://github.com/mierak/rmpc/pull/156 and available on build from master. I will improve on this in future as well.
