### ISSUE TITLE
Scrolling through playlists is slow

### ISSUE THREAD

**Issue by Holzhaus** [mierak/rmpc#160]
### Description

When navigating through the playlists in the playlists tab using the arrow keys, the entire applications starts to lag. 

### Steps to reproduce

When holding and then releasing the down arrow key, the application keeps going through the playlists for some time and is unresponsive to user input. To reproduce, use a very slow MPC server, e.g. and old RPi with a slow external HDD :sweat_smile: 

### Expected behavior

ncmpcpp is quite fast in comparison. I assume the main reason is that the actual loading of the playlist content happens in the background and the request is canceled when the user switches to another playlist before the current one was loaded.

### What terminal emulator are you running rmpc in?

alacritty 0.14.0 (22a44757)

### rmpc debuginfo

<details>
  <summary>rmpc debuginfo</summary>

  ```sh
rmpc 0.6.0 git Arch Linux

Config path          /home/jan/.config/rmpc/config.ron
Theme path           None

MPD:
Address              "127.0.0.1:6600"
Resolved Address     IpAndPort("raspberrypi-4b.lan:6600")
MPD_HOST             raspberrypi-4b.lan
MPD_PORT             unset

Youtube playback:
Cache dir            None
ffmpeg               installed       ffmpeg version n7.1 Copyright (c) 2000-2024 the FFmpeg developers
ffprobe              installed       ffprobe version n7.1 Copyright (c) 2007-2024 the FFmpeg developers
yt-dlp               not installed   Version not available
python3              installed       Python 3.12.7
python-mutagen       installed       PRESENT

Image protocol:
Requested            Auto
Resolved             Unsupported
TMUX                 false
ueberzugpp           not installed   Version not available  
```
</details>
alacritty

### Config file

default config

### Relevant log output

n/a

**Comment by mierak** [comment]
Yeah that is an issue with how the update loop is setup in rmpc: `keypress -> push to queue -> read from queue -> start rendering frame -> request data from mpd -> finish render`. There is no way to cancel/discard in flight requests at the moment, but I agree that has to change somehow. 

We could sort of get around this by quickly caching the results instead of refetching on every change, but it would not solve the issue for the first pass through the playlists.

**Comment by Holzhaus** [comment]
Awesome.

Here's what pressing and holding the up/down buttons on the main branch look like (yes, it really hands that long, i didn't release the button until after I stopped the recording):

https://github.com/user-attachments/assets/2c74015a-06a3-4490-a463-e993b3bd4e28

And here's how it looks with [refactor/mpd-client-off-ui-thread](https://github.com/mierak/rmpc/tree/refactor/mpd-client-off-ui-thread). Very nice how snappy it looks now:

https://github.com/user-attachments/assets/198bc6ee-b0d4-4c38-8412-8d13e4584a95

**Comment by mierak** [comment]
That is indeed quite a difference! Thanks for trying it out. Hopefully I will get it done sooner than later.

**Comment by mierak** [comment]
https://github.com/mierak/rmpc/pull/167 was merged to master. It was a ton of work so I expect to find some number of (hopefully smaller) issues, but it seems to work fine on my end. You can build from master if you want it now!

**Comment by Holzhaus** [comment]
Thanks! I hope I get around to try this next week.
