### ISSUE TITLE
Update Installation Documentation for mpd

### ISSUE THREAD

**Issue by hakan-demirli** [mierak/rmpc#162]
### Description

mpd is a hard requirement for rmpc. So, `nix run nixpkgs#rmpc` will return error if mpd is not running in the background.

```Error: Message: 'Failed to connect to mpd', inner error: 'Generic("Connection refused (os error 111)")'```

Users has to first launch mpd:
```nix run nixpkgs#mpd -- --no-config```
Then rmpc:
```nix run nixpkgs#rmpc```

This info is missing on the documentation/website. https://mierak.github.io/rmpc/try-without-install/

### Steps to reproduce

* ```pkill mpd```
* ```nix run nixpkgs#rmpc```

### Expected behavior

No errors.

### What terminal emulator are you running rmpc in?

kitty 0.37.0 created by Kovid Goyal

### rmpc debuginfo

<details>
  <summary>rmpc debuginfo</summary>

  ```sh

rmpc 0.6.0 git 0.6.0

Config path          /home/emre/.config/rmpc/config.ron
Theme path           None

MPD:
Address              "127.0.0.1:6600"
Resolved Address     IpAndPort("127.0.0.1:6600")
MPD_HOST             unset
MPD_PORT             unset

Youtube playback:
Cache dir            None
ffmpeg               installed       ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
ffprobe              installed       ffprobe version 7.1 Copyright (c) 2007-2024 the FFmpeg developers
yt-dlp               not installed   Version not available
python3              installed       Python 3.12.7       
python-mutagen       not installed   NOT PRESENT         

Image protocol:
Requested            Auto
Resolved             Kitty
TMUX                 false
ueberzugpp           not installed   Version not available
  ```
</details>

### Config file

No config.

### Relevant log output

No such file `/tmp/rmpc.log`

**Comment by hakan-demirli** [comment]
I suggest adding smth like this:

```nix run nixpkgs#mpd -- --no-config &&  nix run nixpkgs#rmpc```

**Comment by mierak** [comment]
Same goes for the normal installation/try script. It being an MPD client should imply the requirement but I guess its not clear enough. I think better would be just mentioning it at the top of that page.
