### ISSUE TITLE
Lyrics shift by one line 

### ISSUE THREAD

**Issue by NischalDawadi** [mierak/rmpc#175]
### Description

https://imgur.com/KxZVJkq (Video)
[01. Alice In Chains - Rotten Apple (Album Version).txt](https://github.com/user-attachments/files/18137194/01.Alice.In.Chains.-.Rotten.Apple.Album.Version.txt)
I uploaded lyrics in txt because github didn't support lrc .
As you can see in the video the lyrics highlights one sentence fast the sung one.
I tried with three four different songs it's same for others as well

### Steps to reproduce

By using the lyrics pane.

### rmpc debuginfo

rmpc 0.6.0 git 33027ab

Config path          /home/hypr/.config/rmpc/config.ron
Theme path           Some("wallust")

MPD:
Address              "127.0.0.1:6600"
Resolved Address     IpAndPort("127.0.0.1:6600")
MPD_HOST             unset
MPD_PORT             unset

Youtube playback:
Cache dir            Some("/home/hypr/.cache/rmpc/")
ffmpeg               installed       ffmpeg version 6.1.2 Copyright (c) 2000-2024 the FFmpeg developers
ffprobe              installed       ffprobe version 6.1.2 Copyright (c) 2007-2024 the FFmpeg developers
yt-dlp               installed       2024.09.27          
python3              installed       Python 3.12.7       
python-mutagen       installed       PRESENT             

Image protocol:
Requested            Auto
Resolved             Kitty
TMUX                 false
ueberzugpp           not installed   Version not available

### Config file

#![enable(implicit_some)]
#![enable(unwrap_newtypes)]
#![enable(unwrap_variant_newtypes)]
(
address: "127.0.0.1:6600",
on_song_change: ["~/.config/rmpc/notify"],
lyrics_dir: "~/.lyrics",
theme: Some("wallust"), 
cache_dir: Some("/home/hypr/.cache/rmpc/"),

volume_step: 5,
status_update_interval_ms: 1000,
wrap_navigation: false,
enable_mouse: true,
album_art: (
method: Auto,
max_size_px: (width: 600, height: 600),
),
keybinds: (
global: {
":": CommandMode,
"3": ArtistsTab,
",": VolumeDown,
"s": Stop,
".": VolumeUp,
"c": ToggleSingle,
"1": QueueTab,
"6": SearchTab,
"": NextTab,
"": NextTab,
"5": PlaylistsTab,
"": PreviousTab,
"": PreviousTab,
"q": Quit,
"4": AlbumsTab,
"x": ToggleRandom,
">": NextTrack,
"<": PreviousTrack,
"f": SeekForward,
"v": ToggleConsume,
"2": DirectoriesTab,
"p": TogglePause,
"z": ToggleRepeat,
"b": SeekBack,
"~": ShowHelp,
"O": ShowOutputs,
},
navigation: {
"": UpHalf,
"N": PreviousResult,
"a": Add,
"r": Rename,
"n": NextResult,
"g": Top,
"": Select,
"G": Bottom,
"h": Left,
"": Confirm,
"i": FocusInput,
"J": MoveDown,
"j": Down,
"": DownHalf,
"/": EnterSearch,
            "<C-c>":     Close,

            "<Esc>":     Close,
"K": MoveUp,
"l": Right,
"D": Delete,
"k": Up,
},

    queue: {
        "D":       DeleteAll,
        "<CR>":    Play,
        "<C-s>":   Save,
        "a":       AddToPlaylist,
        "d":       Delete,
        "i":       ShowInfo,
                },
                   ),
 tabs: [
 (
        name: "Queue",
        border_type: None,
        pane: Split(
            direction: Horizontal,
            panes: [
                (
                    size: "45%",
                    pane: Split(
                        direction: Vertical,
                        panes: [
                            (
                                size: "10%",
                                pane: Pane(Lyrics),
                            ),
                            (
                                size: "90%",
                                pane: Pane(AlbumArt),
                            )
                        ]
                    ),
                ),
                (
                    size: "55%",
                    pane: Pane(Queue),
                       ),
                ],
            ),
        ),
         (

            name: "Directories",

            border_type: Full,

            pane: Pane(Directories),

        ),

        (

            name: "Artists",

            border_type: None,

            pane: Pane(Artists),

        ),

        (

            name: "Album Artists",

            border_type: None,

            pane: Pane(AlbumArtists),

        ),

        (

            name: "Albums",

            border_type: None,

            pane: Pane(Albums),

        ),

        (

            name: "Playlists",

            border_type: None,

            pane: Pane(Playlists),

        ),

        (

            name: "Search",

            border_type: None,

            pane: Pane(Search),

        ),
    
],
)

### Relevant log output

<details>
  <summary>rmpc log</summary>

  ```
Paste the contents here
  ```
</details>

**Comment by mierak** [comment]
Thanks, should be fixed in https://github.com/mierak/rmpc/pull/176.
