### ISSUE TITLE
Cover art as spinning music disc

### ISSUE THREAD

**Issue by TwinkleByte** [mierak/rmpc#191]
### Description

![ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/8735710f-b4e7-4fd7-9bce-8111ec13b4d7)

Add option to make the cover art turn into a spinning music disc.

I got this idea from a extension in spicetify called 'Spinning CD Cover Art'

### Proposed solution

I'm not sure how this could be achieved since they did it using custom css and not rust. Still as reference, this is how they did it using custom css.

`@keyframes rotating {from {transform: rotate(0deg);}to {transform: rotate(360deg);}}.cover-art {animation: rotating 360s linear infinite;clip-path: circle(50% at 50% 50%);position: relative;}.cover-art::after {content: '';position: absolute;top: 50%;left: 50%;transform: translate(-50%, -50%);width: 22%;height: 22%;background: radial-gradient( circle at center, rgba(24, 22, 35, 0.9) 0%, rgba(24, 22, 35, 0.9) 38%, rgba(255, 255, 255, 0.1) 38%, rgba(255, 255, 255, 0.1) 40%, rgba(24, 22, 35, 0.9) 40%, rgba(24, 22, 35, 0.9) 100% ), repeating-radial-gradient( circle at center, rgba(255, 255, 255, 0.1) 0, rgba(255, 255, 255, 0.1) 1px, transparent 1px, transparent 4px );border-radius: 50%;pointer-events: none;box-shadow: 0 0 10px rgba(0, 0, 0, 0.3) inset, 0 0 20px rgba(255, 255, 255, 0.1);}.cover-art::before {content: '';position: absolute;top: 50%;left: 50%;transform: translate(-50%, -50%);width: 6%;height: 6%;background: rgba(24, 22, 35, 1);border-radius: 50%;box-shadow: 0 0 5px rgba(255, 255, 255, 0.2);z-index: 1;} .main-nowPlayingBar-left button {background: transparent;}`

**Comment by mierak** [comment]
There is no CSS in terminal emulators, we are limited by what the various graphics protocols allow us to do.

rmpc supports animated cover arts with [kitty](https://mierak.github.io/rmpc/release/configuration/album-art/#kitty) and [iterm2](https://mierak.github.io/rmpc/release/configuration/album-art/#iterm2-inline-image-protocol) with their respected caveats. If you want this effect you can create those as animated gifs and embed them in your files.
