### ISSUE TITLE
Generate man pages / shell completions with clap

### ISSUE THREAD

**Issue by donovanglover** [mierak/rmpc#20]
Should be possible to add man pages / shell completions with relative ease since rmpc already uses clap for the cli.

For my own projects I use a [build.rs](https://github.com/donovanglover/hyprdim/blob/2.2.5/build.rs) script that generates these from [cli.rs](https://github.com/donovanglover/hyprdim/blob/2.2.5/src/cli.rs)

**Comment by mierak** [comment]
Yup, this is definitely on my radar

**Comment by mierak** [comment]
Thank you for providing examples from your project. I have customized it a little bit and merged here https://github.com/mierak/rmpc/pull/24 if that is alright with you. With that said, completions and man pages should now generate on build inside the target directory.
