### ISSUE TITLE
cursor not following playback

### ISSUE THREAD

**Issue by mustaruhtinas** [mierak/rmpc#27]
When in the queue tab (1), I cannot seem to be able to make the cursor follow playback. Is it an intended behaviour or some sort of error / missing config option?

**Comment by mierak** [comment]
What do you mean by cursor? The progress bar at the bottom of the screen or the currently highlighted song in the table itself?

Regarding the table, there are three types of items
* Songs in the queue with a white foreground
* The currently playing song with a blue foreground which changes with playback
* And lastly the highlighted one with blue background which changes only on user input.
![image](https://github.com/user-attachments/assets/078ea902-f701-49b9-b4c4-c2478de8eaca)

If you mean the progress bar, then its a bug. Could you reproduce the issue and provide me with `/tmp/rmpc.log` if that is the case?

**Comment by mustaruhtinas** [comment]
Sorry for not being more specific.
It is indeed about the highlighted entry with the blue background. Since it is changing only on user input then it means it is its intended behaviour.

**Comment by mierak** [comment]
No problem. I have looked at how ncmpcpp handles it and it behaves as you want it. I have added an option to get this behaviour in https://github.com/mierak/rmpc/pull/28.
You can rebuild from master and adjust your config.ron
```rust
(
    address: "/tmp/mpd_socket",
    status_update_interval_ms: 1000,
    select_current_song_on_change: true,
```
https://mierak.github.io/rmpc/configuration/#select_current_song_on_change

**Comment by mustaruhtinas** [comment]
Thank you, working great.
