### ISSUE TITLE
Use filename as title when missing metadata

### ISSUE THREAD

**Issue by diegodorado** [mierak/rmpc#38]
THis is more an ask than an issue, because mpd lsinfo cmd returns "Untitled" as title for untagged audio files, and "Unknown" for album and artist.

While I know there a cli tools to "fix" these files metadata, the issue I have is that I want to explore a collection of sort audio samples where their filenames are enough to identify them, and I wouldn't want to maintain their metadata (using their filename as title) every time something changes on my collection.

Would it be possible that `rmpc` fallsback to filename instead of the "Untitled" title reported by lsinfo?

Here's a screenshot to understand the issue:
![image](https://github.com/user-attachments/assets/36fc2eaf-a1db-42f1-b8af-7ea39f72cf55)

**Comment by mierak** [comment]
The "Untitled" and "Unknown" are hardcoded values directly in rmpc, `lsinfo` simply does not return the value at all.

Anyway, for the middle column, that is actually a configurable format. What you see is the default of `<track> <artist> <title>` where missing `<track>` fallsback to `--` and missing `<artist>` falls back to `Unknown Artist`. Missing `<title>` does not fallback to anything by default(I should probably change that). More on that [here](https://mierak.github.io/rmpc/configuration/theme/#browser_song_format) and an example of default config can be found on the [default theme page](https://mierak.github.io/rmpc/reference/theme/) at the very bottom. 

You can configure the fallback to `Filename` there. But I see now that I have a bug in there, filename is in fact the full path, the one which MPD reports as `file`. I will add a new `File` property and change behavior of the current `Filename` to return really just a filename.

And as for the rightmost column, I guess the better behavior here would be to always show the full `file` as reported by MPD and maybe omit the Title/Artist/Album completely if they are not present in the metadata?

**Comment by mierak** [comment]
Would changes in https://github.com/mierak/rmpc/pull/39 resolve your issue?

**Comment by diegodorado** [comment]
oh, you're so kind! checking now, thanks!

**Comment by diegodorado** [comment]
That worked perfectly, thanks!!
![image](https://github.com/user-attachments/assets/d99e5792-123a-49a4-93f3-53b8ca523e2d)

**Comment by mierak** [comment]
Great! You're welcome.
