### ISSUE TITLE
how to make pywal/wallust colorscheme to work with rmpc 

### ISSUE THREAD

**Issue by NischalDawadi** [mierak/rmpc#44]
Same as title

**Comment by mierak** [comment]
What have you tried and what is not working? Hard to help like this. I do not use pywal and do not know wallust, but for pywal you can use [their templating function](https://github.com/dylanaraps/pywal/wiki/User-Template-Files) which should simply work.

**Comment by NischalDawadi** [comment]
in ncmpcpp i used to do this
`~include '~/.config/wallust/templates/colors-kitty.conf'`
in rmpc i cannot do this.
Also, unrelated but just like ncmpcpp is there any way I use send notification with album art on song change.

**Comment by mierak** [comment]
So I installed wallust and got it to work, heres the steps:

1. Copy contents of the [default theme](https://mierak.github.io/rmpc/reference/theme/) (including the three directives at the top!) to `~/.config/wallust/templates/rmpc.ron`
2. Change the values inside the theme to your liking, for example you can do
```rust
#![enable(implicit_some)]
#![enable(unwrap_newtypes)]
#![enable(unwrap_variant_newtypes)]
(
    background_color: Some("{{background}}"),
    text_color: Some("{{foreground}}"),
...
```
3. Define a template section in your wallust config like so 
 ```toml
[templates]
rmpc = { template = 'templates/rmpc.ron', target = '~/.config/rmpc/themes/wallust.ron', new_engine = true }
```
4. Set your theme in `~/.config/rmpc/config.ron` 
```rust
#![enable(implicit_some)]
#![enable(unwrap_newtypes)]
#![enable(unwrap_variant_newtypes)]
(
    address: "/tmp/mpd_socket",
    theme: Some("wallust"), // here!
```
5.  run `wallust` and restart `rmpc`

**Comment by mierak** [comment]
And no, there is currently no way to send notification on song change. Ncmpcpp does this by allowing you to execute a custom script on song change right? Sounds like a nice enhancement to me, I will make that happen.

**Comment by NischalDawadi** [comment]
Thank you so much. It works perfectly now. 
Now after you implement the custom script, i think i am going to ditch ncmpcpp for this.

**Comment by mierak** [comment]
Just a heads up, I have merged https://github.com/mierak/rmpc/pull/46 which contains `on_song_change` property. I have also taken documented an example of desktop notification with album art provided your notification daemon supports `notify-send`'s icons. You can check it out [here in the docs](https://mierak.github.io/rmpc/guides/on_song_change/)

**Comment by NischalDawadi** [comment]
Amazing work. This project deserves more stars.
