### ISSUE TITLE
trying rmpc but cant launch

### ISSUE THREAD

**Issue by r3k2** [mierak/rmpc#50]
GNU/Linux
Wayland
Sway
using mopidy with mopidy-mpd (for mpd clients)

I am a bit tired of old ncmcpp so im out looking for a new TUI client 
but when I run rmpc I get

```
Error: Message: 'Failed to create app state', inner error: 'ParseError: 'invalid digit found in string''
```

any plans to support the standard in linux? "sixel" I run foot/alacritty terminal.

**Comment by mierak** [comment]
> any plans to support the standard in linux? "sixel" I run foot/alacritty terminal.

Sixel is already supported. I test foot specifically. Alacritty does not support sixel, but there is some fork that does iirc  (album art would still work with ueberzugpp).

Now for the error, thats a new one. This basically means that MPD (i guess in your case its mopidy?) returned some invalid/unexpected data when rmpc was trying to query MPD's status.

Looking into the issue further, it seems mopidy reports MPD protocol version `0.19.0`, but rmpc was built fairly recently all things considered with protocol version `0.23.5` in mind as thats been released for three years now. Mopidy's protocol version does not even support commads like `getvol`, `albumart` or `readpicture` which rmpc uses extensively. 

Seems like there was some activity in the direction of at least supporting the album art protocol bits https://github.com/mopidy/mopidy-mpd/pull/57 but was abandoned.

So to close this, even if we diagnose your issue (which I am open to), all kind of weirdness will probably happen. And even if we sort all the weirdness, album arts will simply not work without the pull request above merged into mopidy-mpd.
I guess the only proper advice I can give you is to switch to MPD 😟 Is there some sort of feature that is blocking you from using MPD and not mopidy?

**Comment by r3k2** [comment]
@mierak thanks for the detail reply, unfortunately I work 80 hours a week and only Friday, Sat, Sun is when I can focus on personal things :/  the reason I use mopidy is that I do not listen to music from my local computer, I have a rasperry pi with my mp3's yes, but mostly I listen to radios and other stuff that mopidy does have many plugins for like https://mopidy.com/ext/ specially this one https://mopidy.com/ext/tunein/
I like mpd/mopidy to not have to use electron/javascript/browsers to do my music listening is why I use 99% of TUI tools like mcmcpp, but I am looking for something more modern in GO/Rust etc. with a more modern UI is why I wanted to you give your project a try :man_shrugging: 

I will create an issue with mopidy-mpd see what's the problem thank you!

**Comment by mierak** [comment]
Thanks for creating the issue. Feel free to reopen this one if mopidy's side gets sorted out and there is some work to be done on rmpc's side.
