### ISSUE TITLE
Switching tabs does not redraw content anymore

### ISSUE THREAD

**Issue by soifou** [mierak/rmpc#77]
Upgraded to 0.5 and notice when switching between tabs, the output does not get cleared. I did not have this problem with previous version.

![image](https://github.com/user-attachments/assets/f520c786-317f-4b64-b388-8afbd44a74ae)

Tried with default config, same problem. Resizing the terminal force the redraw however.
I'm using kitty, latest version (0.36.4).

**Comment by mierak** [comment]
Hi, thanks for the report. 
I assume you are switching tabs with the direct key keybinds, does the screen get cleared when switching tabs with `NextTab` and `PreviousTab` (Left/RIght arrow by default)?

**Comment by soifou** [comment]
Spotted! 

`NextTab` and `PreviousTab` work fine but `SwitchToTab` don't

**Comment by mierak** [comment]
Should be fixed in #78. Thanks again for the report!
