### ISSUE TITLE
Arrow keys in Queue support?

### ISSUE THREAD

**Issue by Solarunit** [mierak/rmpc#79]
Is it possible to use Arrow keys in Queue tab? Like Up and Down.

**Comment by mierak** [comment]
Keybinds are customizable. https://mierak.github.io/rmpc/configuration/keybinds/#navigation
in your config.ron

```
...
navigation: {
    "<Up>":         Up,
    "<Down>":       Down,
...
```
Note that navigation kebyinds are shared among the tabs. So by doing this change, arrow keys will be used even for the browser tabs etc. You can bind more than one key to a single action.

**Comment by Solarunit** [comment]
I see, I was expected to have them by default thought like in ncmpcpp

**Comment by mierak** [comment]
Defaults are vim-like, so hjkl for navigation. A user is expected to set up their own config and change them as the see fit.

**Comment by Solarunit** [comment]
well, I personally never use hjkl for navigation

**Comment by mierak** [comment]
Myself and many others do. Default values simply cannot satisfy everybody, that is why we have configurable keybinds, which you can find in the docs linked above.

**Comment by Solarunit** [comment]
what about option in the config something like `disable vim-bindings` that would activate "normal" bindings? :slightly_smiling_face:

**Comment by mierak** [comment]
Why is that needed when you can just change the keybinds yourself, this would just be a redundant behavior? Introducing extra config option just makes single default values into a set of two default values. They will still not fit every usecase.

Better option would be providing secondary [reference config](https://mierak.github.io/rmpc/reference/config/) with arrow keys instead of hjkl, home/end instead of G and g etc.

**Comment by Solarunit** [comment]
I think Arrow keys navigation is more user friendly and it's expected to work out of the box.

Can it co-exists with vim-bindings at the same time?

**Comment by mierak** [comment]
Sorry, had to go last night. I think arrow keys alongside hjkl make sense yeah. Shame that it is a breaking change, since left/right arrows were used to change tabs, but hopefully this is for the better. Fixed in https://github.com/mierak/rmpc/pull/82.

**Comment by Solarunit** [comment]
Maybe for tabs switching we could use `shift+left/right` or `ctrl+shift+left/right`, though  `ctrl+shift+left/right` is already used for switching tabs in kitty I think.

**Comment by mierak** [comment]
I think its fine the way it is now, left/right arrow keys were already duplicates of tab for next tab and shift tab for previous tab, so those are left in.
