### ISSUE TITLE
Mouse support?

### ISSUE THREAD

**Issue by Solarunit** [mierak/rmpc#81]
Is mouse supported?
If not, do you plan to add Mouse support in the future?

**Comment by mierak** [comment]
Mouse is currently not supported. I plan to add some rudimentary support eventually, but no promises when it is going to happen.

**Comment by mierak** [comment]
just a heads up, I got around to it a bit earlier than expected https://mierak.github.io/rmpc/guides/mouse_controls/

**Comment by Solarunit** [comment]
nice! I gonna test it in the next release, thanks
