### ISSUE TITLE
Covers rendering ontop of other tmux windows when unfocused

### ISSUE THREAD

**Issue by teaperr** [mierak/rmpc#93]
# Expected Behavior
Rendered covers to be not visible when rmpc is on an unfocused tmux window

# Actual Behavior
When rmpc is open in another window in tmux and the song changes, the cover will be rendered on top of the current tmux pane until the current rmpc instance is quit.
## Steps to reproduce:
1. Open two tmux windows.
2. Run rmpc in one of them.
3. Play music.
4. Move to the other window.
5. run "rmpc next".

Specifications

    Version: rmpc 0.4.0
    Platform: Nixos Unstable
    Additional info: 
        Terminal: Alacritty 0.13.2

Screenshots:

![image](https://github.com/user-attachments/assets/b95e6665-275a-4d21-99f6-565678a6843a)

**Comment by mierak** [comment]
Right, this happens because ueberzugpp runs in a separate process and rmpc does not detect that it is not in an active tmux pane. I will see if I can somehow detect that.
Anyway, this should really only happen in terminals not supported by other protocols like kitty.

**Comment by mierak** [comment]
There is also related issue https://github.com/jstkdng/ueberzugpp/issues/213 and pull request https://github.com/jstkdng/ueberzugpp/pull/215 on ueberzugpp side which could resolve this issue.

**Comment by mierak** [comment]
Fixed by https://github.com/mierak/rmpc/pull/95
Unfortunately the fix is not perfect. When you repeat your steps to reproduce and then switch back to rmpc, the album art will be the same as when you have moved to the other window. Simply switching to another tab in rmpc and back will refresh it though.

I will eventually improve on this, but this should make it at least usable.

**Comment by teaperr** [comment]
great, thanks a lot!

**Comment by s0rau** [comment]
I'm using sway and alacritty and rmpc so in virtual desktop i've rmpc opened in alacritty in other virtual desktop the cover art is on the top my firefox after run mpc next.
Do you have any solution about that ?

**Comment by mierak** [comment]
Do not use alacritty, use a terminal that supports images, ueberzugg has its limitations and this is one of them.

Rmpc has no idea about workspaces/tags/desktops and a "solution" would require separate implementation for sway, hyprland, kde, gnome, river, niri, .... you name it which is not happening.

**Comment by s0rau** [comment]
Thanks for answer.

I've installed kitty but the results is the same.

Yes you're right, I but I don't know how to well explain the situation, the cover is still on top of all application

**Comment by mierak** [comment]
Open a proper bug report and include the debuginfo and some screenshots or recording so we can take a closer look at it.
