### ISSUE TITLE
[FR] Navlist enhancements

### ISSUE THREAD

**Issue by soifou** [mierak/rmpc#96]
When you are on the last item on any list, pressing `Down` go to the first item and conversely, pressing `Up` on the first item go to last item.

I think allowing to 'cycle' should be an opt-in behaviour. By default, as in ncmpcpp, a sane way would be to do... nothing. If I need to go to first/last, `Top/Bottom` actions can already do that.

In the same registry, a "nice to have" would be to implement a `scrolloff` option like in vim (minimal number of screen lines to keep above and below the current selected item) so we could better predict what will go next/prev.

**Comment by soifou** [comment]
Wow... that was fast! I'm using it right now and it works nicely, thanks!

**Comment by mierak** [comment]
Glad it works fine! Anyway, the wrapping is now gone by default and can be configured back with https://mierak.github.io/rmpc/configuration/#wrap_navigation.

**Comment by soifou** [comment]
Mini feedback, I noticed the scrollback indicator is not in phase anymore. When the first item is selected, the scrollback is not at the very top but slightly below, and on a (very) long list, it disappears on the last items.

It looks like a regression.

**Comment by mierak** [comment]
Hmm, I cant seem to reproduce. Can you give me more info? Config and theme, terminal and maybe a screenshot would help.

**Comment by soifou** [comment]
Sure, I tracked down the issue and the culprit seems to be the symbols used for the scrollbar:

```ron
    scrollbar: (
        symbols: ["", "┃", "", ""],
        // ...
    ),
```

If I change with the default, there is no problem. I did not notice this in previous version.

**Comment by mierak** [comment]
Thanks! I see the problem now. Though for me its been there since forever, at least since 0.4.0. I'll look into it!

**Comment by mierak** [comment]
Fix is merged to master https://github.com/mierak/rmpc/pull/100

**Comment by soifou** [comment]
Confirmed 👍 thanks again :)
